# Generated by Django 4.1.2 on 2022-10-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('artista', models.CharField(max_length=150, verbose_name='Artista')),
                ('genero', models.CharField(max_length=150, verbose_name='Gênero')),
                ('dt_lacamento', models.DateField(verbose_name='Lançamento')),
                ('audio', models.FileField(upload_to='', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albuns',
            },
        ),
    ]
