# Generated by Django 4.1.2 on 2022-10-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('artista', models.CharField(max_length=150, verbose_name='Artista')),
                ('album', models.CharField(max_length=150, verbose_name='Album')),
                ('genero', models.CharField(max_length=150, verbose_name='Gênero')),
                ('dt_lacamento', models.DateField(verbose_name='Lançamento')),
                ('audio', models.FileField(upload_to='', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
            },
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
